### ISSUE TITLE
Class 'NFe' not found

### ISSUE THREAD

**Issue by berbare** [nfe/client-php#15]
Desde a versão `2.5`, que introduziu a PR #11 na master, nosso módulo que se comunica com o NFEio parou de funcionar devido à mudança no nome da principal classe.

Acho que uma mudança desse nível deveria ser introduzida com mais cautela (como opcional, configurável) ou como major (versão `3.x`). Estávamos configurados para aceitar o pacote nas versões `"^2.4"`, mas tive que alterar para fixar em `"2.4"` agora.

**Comment by gblmarquez** [comment]
@berbare obrigado pelo feedback. 

Porém tivemos que realizar essa mudanças com um pouco de agilidade, foi devido a diversos conflitos pela falta do PSR.

A alteração que fizemos foi mudar o nome da classe de NFe para NFe_io.

**Comment by byjg** [comment]
Nesses casos, quando a mudança é grande, o correto é fazer o update da Major Release, ou seja, passaria de 2.4 para 3.0. Assim nao quebraria quem utiliza o gerenciamento de versão corretamente.

**Comment by gblmarquez** [comment]
@byjg valeu pela dica. Na próxima vamos proceder nesse sentido.
