### ISSUE TITLE
Incompatibilidade NFE.io - Iugu

### ISSUE THREAD

**Issue by badrianpg** [nfe/client-php#5]
Olá!
Tentei usar o composer para instalar o nfe.io (https://github.com/nfe/client-php), no entanto, já temos instalado (via composer também) o pacote do Iugu. Inclusive nossa ideia aqui é integrar as duas ferramentas relacionando o pagamento do Iugu com a geração de notas no Nfe.io.
Porém ao fazer a instalação temos as seguintes incompatibilidades:
Warning: Ambiguous class resolution, "APIResource" was found in both "/path/vendor/nfe/nfe/lib/Nfe/APIResource.php" and "/path/vendor/iugu/iugu/lib/Iugu/APIResource.php", the first will be used.
Warning: Ambiguous class resolution, "APIChildResource" was found in both "/path/vendor/nfe/nfe/lib/Nfe/APIChildResource.php" and "/path/vendor/iugu/iugu/lib/Iugu/APIChildResource.php", the first will be used.
Warning: Ambiguous class resolution, "class_tools" was found in both "/path/vendor/nfe/nfe/lib/Nfe/Backward_Compatibility.php" and "/path/vendor/iugu/iugu/lib/Iugu/Backward_Compatibility.php", the first will be used.

Como proceder neste caso?

Obrigado!

**Comment by renatonascalves** [comment]
@badrianpg 

Um tempo atrás eu vi algo parecido e era referente a versão desatualizada do Composer. Pesquisei aqui o issue no repo do Composer e achei o pull que corrigiu isso.

https://github.com/composer/composer/commit/05d9912f97a2decf6a5c08dfa569dcf23d79b16d

Então, você pode atualizar a versão do Composer com o seguinte comando:

composer selfupdate

Veja se resolve seu problema. Aguardo teu feedback.

**Comment by badrianpg** [comment]
@renatonascalves 

Fiz a atualização pedida. Mas estou com a versão atualizada do composer:
**Composer version 1.1.2 2016-05-31 19:48:11**

E infelizmente não corrigiu meu problema.

**Comment by renatonascalves** [comment]
@badrianpg Confirmei o seu problema! Devo está subindo uma correção em breve.

**Comment by renatonascalves** [comment]
@badrianpg Atualize com a versão 1.0.1 para corrigir esse problema.

https://github.com/nfe/client-php/releases/tag/1.0.1

**Comment by badrianpg** [comment]
Olá @renatonascalves 

Fiz a atualização mas aparentemente a questão se manteve. Segue lista de comandos:

$ composer selfupdate
You are already using composer version 1.1.3 (stable channel).
$ composer require nfe/nfe:1.0.1
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
Warning: Ambiguous class resolution, "APIResource" was found in both "/path/vendor/nfe/nfe/lib/Nfe/NFe_APIResource.php" and "/path/vendor/iugu/iugu/lib/Iugu/APIResource.php", the first will be used.
Warning: Ambiguous class resolution, "APIChildResource" was found in both "/path/vendor/nfe/nfe/lib/Nfe/NFe_APIChildResource.php" and "/path/vendor/iugu/iugu/lib/Iugu/APIChildResource.php", the first will be used.

Faltou alguma ação a ser feita?

**Comment by renatonascalves** [comment]
Não, está correto! 

@badrianpg Eu não consigo reproduzir esse erro que está tendo... :/

Altere a classe do client-php de NFe_APIResource para NFeAPIResource. Veja se o erro é removido.

**Comment by gblmarquez** [comment]
@badrianpg acabamos de subir uma nova versão 1.0.2 que deve corrigir, por favor testar.

**Comment by badrianpg** [comment]
@gblmarquez @renatonascalves 
Realmente! Na v1.0.2 a incompatibilidade foi resolvida!
Vou partir para a utilização da API agora!
Obrigado pessoal!
